import globals from 'globals'
import js from '@eslint/js'

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2024,
      sourceType : 'module',
      globals    : {
        ...globals.node,
      },
    },

    ignores: ['node_modules/**'],

    rules: {
      'accessor-pairs'        : 'off',
      'array-bracket-newline' : ['error', {'minItems': 5, 'multiline': true}],
      'array-bracket-spacing' : ['error', 'never'],
      'array-callback-return' : 'off',
      'array-element-newline' : 'off',
      'arrow-body-style'      : 'off',
      'arrow-parens'          : ['error', 'as-needed'],
      'arrow-spacing'         : 'off',
      'block-scoped-var'      : 'off',
      'block-spacing'         : ['error', 'never'],
      'brace-style'           : ['error', '1tbs'],
      'callback-return'       : 'off',
      'camelcase'             : 'off',
      'capitalized-comments'  : 'off',
      'class-methods-use-this': 'off',
      'comma-dangle'          : [
        'error',
        {
          'arrays'   : 'always-multiline',
          'exports'  : 'always-multiline',
          'functions': 'always-multiline',
          'imports'  : 'always-multiline',
          'objects'  : 'always-multiline',
        },
      ],
      'comma-spacing'              : 'error',
      'comma-style'                : 'error',
      'complexity'                 : 'off',
      'computed-property-spacing'  : 'error',
      'consistent-return'          : 'off',
      'consistent-this'            : 'off',
      'constructor-super'          : 'error',
      'curly'                      : 'off',
      'default-case'               : 'off',
      'dot-location'               : 'off',
      'dot-notation'               : 'off',
      'eol-last'                   : 'error',
      'eqeqeq'                     : 'error',
      'for-direction'              : 'off',
      'func-call-spacing'          : 'error',
      'func-name-matching'         : 'off',
      'func-names'                 : 'off',
      'func-style'                 : 'off',
      'function-paren-newline'     : 'off',
      'generator-star-spacing'     : ['error', 'after'],
      'getter-return'              : 'off',
      'global-require'             : 'off',
      'guard-for-in'               : 'off',
      'handle-callback-err'        : 'off',
      'id-blacklist'               : 'off',
      'id-length'                  : 'off',
      'id-match'                   : 'off',
      'implicit-arrow-linebreak'   : 'off',
      'indent'                     : ['error', 2, {'SwitchCase': 1}],
      'indent-legacy'              : 'off',
      'init-declarations'          : 'off',
      'jsx-quotes'                 : 'off',
      'key-spacing'                : ['error', {'align': 'colon'}],
      'keyword-spacing'            : 'error',
      'line-comment-position'      : 'off',
      'linebreak-style'            : 'error',
      'lines-around-comment'       : 'off',
      'lines-around-directive'     : 'off',
      'lines-between-class-members': 'off',
      'max-depth'                  : 'off',
      'max-len'                    : [
        'error',
        {
          'code'                : 160,
          'ignoreComments'      : true,
          'ignoreRegExpLiterals': true,
          'tabWidth'            : 2,
        },
      ],
      'max-lines'              : 'off',
      'max-nested-callbacks'   : 'off',
      'max-params'             : 'off',
      'max-statements'         : 'off',
      'max-statements-per-line': 'off',
      'multiline-comment-style': 'off',
      'multiline-ternary'      : 'off',
      'new-cap'                : [
        'error',
        {
          'capIsNew': false,
        },
      ],
      'new-parens'              : 'off',
      'newline-after-var'       : 'off',
      'newline-before-return'   : 'off',
      'newline-per-chained-call': 'off',
      'no-alert'                : 'off',
      'no-array-constructor'    : 'error',
      'no-await-in-loop'        : 'error',
      'no-bitwise'              : 'off',
      'no-buffer-constructor'   : 'off',
      'no-caller'               : 'error',
      'no-case-declarations'    : 'error',
      'no-catch-shadow'         : 'off',
      'no-class-assign'         : 'error',
      'no-compare-neg-zero'     : 'error',
      'no-cond-assign'          : 'error',
      'no-confusing-arrow'      : 'off',
      'no-console'              : 'off',
      'no-const-assign'         : 'error',
      'no-constant-condition'   : 'error',
      'no-continue'             : 'off',
      'no-control-regex'        : 'error',
      'no-debugger'             : 'error',
      'no-delete-var'           : 'error',
      'no-div-regex'            : 'off',
      'no-dupe-args'            : 'error',
      'no-dupe-class-members'   : 'error',
      'no-dupe-keys'            : 'error',
      'no-duplicate-case'       : 'error',
      'no-duplicate-imports'    : 'off',
      'no-else-return'          : ['error', {'allowElseIf': false}],
      'no-empty'                : 'error',
      'no-empty-character-class': 'error',
      'no-empty-function'       : 'off',
      'no-empty-pattern'        : 'error',
      'no-eq-null'              : 'off',
      'no-eval'                 : 'off',
      'no-ex-assign'            : 'error',
      'no-extend-native'        : 'error',
      'no-extra-bind'           : 'error',
      'no-extra-boolean-cast'   : 'error',
      'no-extra-label'          : 'off',
      'no-extra-parens'         : 'error',
      'no-extra-semi'           : 'error',
      'no-fallthrough'          : 'error',
      'no-floating-decimal'     : 'off',
      'no-func-assign'          : 'error',
      'no-global-assign'        : 'error',
      'no-implicit-coercion'    : 'error',
      'no-implicit-globals'     : 'off',
      'no-implied-eval'         : 'off',
      'no-inline-comments'      : 'off',
      'no-inner-declarations'   : 'error',
      'no-invalid-regexp'       : 'error',
      // 'no-invalid-this'         : 'error',
      'no-irregular-whitespace' : 'error',
      'no-iterator'             : 'off',
      'no-label-var'            : 'off',
      'no-labels'               : 'off',
      'no-lone-blocks'          : 'error',
      'no-lonely-if'            : 'off',
      'no-loop-func'            : 'error',
      'no-magic-numbers'        : 'off',
      'no-mixed-operators'      : 'off',
      'no-mixed-requires'       : 'off',
      'no-mixed-spaces-and-tabs': 'error',
      'no-multi-assign'         : 'off',
      'no-multi-spaces'         : 'error',
      'no-multi-str'            : 'error',
      'no-multiple-empty-lines' : [
        'error',
        {
          'max'   : 2,
          'maxBOF': 0,
          'maxEOF': 1,
        },
      ],
      'no-native-reassign'              : 'off',
      'no-negated-condition'            : 'off',
      'no-negated-in-lhs'               : 'off',
      'no-nested-ternary'               : 'off',
      'no-new'                          : 'off',
      'no-new-func'                     : 'off',
      'no-new-object'                   : 'error',
      'no-new-require'                  : 'off',
      'no-new-symbol'                   : 'error',
      'no-new-wrappers'                 : 'error',
      'no-obj-calls'                    : 'error',
      'no-octal'                        : 'error',
      'no-octal-escape'                 : 'off',
      'no-param-reassign'               : 'off',
      'no-path-concat'                  : 'off',
      'no-plusplus'                     : 'off',
      'no-process-env'                  : 'off',
      'no-process-exit'                 : 'off',
      'no-promise-executor-return'      : 'error',
      'no-proto'                        : 'off',
      'no-prototype-builtins'           : 'off',
      'no-redeclare'                    : 'error',
      'no-regex-spaces'                 : 'error',
      'no-restricted-globals'           : 'off',
      'no-restricted-imports'           : 'off',
      'no-restricted-modules'           : 'off',
      'no-restricted-properties'        : 'off',
      'no-restricted-syntax'            : 'off',
      'no-return-assign'                : 'off',
      'no-return-await'                 : 'error',
      'no-script-url'                   : 'off',
      'no-self-assign'                  : 'error',
      'no-self-compare'                 : 'off',
      'no-sequences'                    : 'off',
      'no-shadow'                       : 'off',
      'no-shadow-restricted-names'      : 'off',
      'no-spaced-func'                  : 'off',
      'no-sparse-arrays'                : 'error',
      'no-sync'                         : 'off',
      'no-tabs'                         : 'error',
      'no-template-curly-in-string'     : 'off',
      'no-ternary'                      : 'off',
      'no-this-before-super'            : 'error',
      'no-throw-literal'                : 'error',
      'no-trailing-spaces'              : 'error',
      'no-undef'                        : 'error',
      'no-undef-init'                   : 'off',
      'no-undefined'                    : 'off',
      'no-underscore-dangle'            : 'off',
      'no-unexpected-multiline'         : 'error',
      'no-unmodified-loop-condition'    : 'off',
      'no-unneeded-ternary'             : 'off',
      'no-unreachable'                  : 'error',
      'no-unsafe-finally'               : 'error',
      'no-unsafe-negation'              : 'error',
      'no-unused-expressions'           : 'off',
      'no-unused-labels'                : 'error',
      'no-unused-vars'                  : 'error',
      'no-use-before-define'            : 'error',
      'no-useless-call'                 : 'off',
      'no-useless-computed-key'         : 'off',
      'no-useless-concat'               : 'off',
      'no-useless-constructor'          : 'off',
      'no-useless-escape'               : 'error',
      'no-useless-rename'               : 'off',
      'no-useless-return'               : 'off',
      'no-var'                          : 'error',
      'no-void'                         : 'off',
      'no-warning-comments'             : 'off',
      'no-whitespace-before-property'   : 'off',
      'no-with'                         : 'error',
      'nonblock-statement-body-position': 'off',
      'object-curly-newline'            : 'off',
      'object-curly-spacing'            : 'error',
      'object-property-newline'         : ['error', {'allowAllPropertiesOnSameLine': true}],
      'object-shorthand'                : 'off',
      'one-var'                         : [
        'error',
        {
          'const': 'never',
          'let'  : 'never',
          'var'  : 'never',
        },
      ],
      'one-var-declaration-per-line'   : 'off',
      'operator-assignment'            : 'off',
      'operator-linebreak'             : 'off',
      'padded-blocks'                  : ['error', 'never'],
      'padding-line-between-statements': [
        'error',
        {
          'blankLine': 'always',
          'next'     : ['return'],
          'prev'     : '*',
        },
      ],
      'prefer-arrow-callback'       : 'off',
      'prefer-const'                : ['error', {'destructuring': 'all'}],
      'prefer-destructuring'        : 'off',
      'prefer-numeric-literals'     : 'off',
      'prefer-promise-reject-errors': 'off',
      'prefer-reflect'              : 'off',
      'prefer-rest-params'          : 'error',
      'prefer-spread'               : 'error',
      'prefer-template'             : 'off',
      'quote-props'                 : ['error', 'consistent'],
      'quotes'                      : [
        'error',
        'single',
        {
          'allowTemplateLiterals': true,
        },
      ],
      'radix'                      : 'off',
      'require-atomic-updates'     : 'off',
      'require-await'              : 'error',
      'require-jsdoc'              : 'off',
      'require-yield'              : 'error',
      'rest-spread-spacing'        : 'error',
      'semi'                       : ['error', 'never'],
      'semi-spacing'               : 'error',
      'semi-style'                 : 'off',
      'sort-imports'               : 'error',
      'sort-keys'                  : 'off',
      'sort-vars'                  : 'off',
      'space-before-blocks'        : 'error',
      'space-before-function-paren': 'error',
      'space-in-parens'            : 'off',
      'space-infix-ops'            : 'error',
      'space-unary-ops'            : 'off',
      'spaced-comment'             : 'error',
      'strict'                     : ['error', 'global'],
      'switch-colon-spacing'       : [
        'error',
        {
          'after' : true,
          'before': true,
        },
      ],
      'symbol-description'    : 'off',
      'template-curly-spacing': 'off',
      'template-tag-spacing'  : 'off',
      'unicode-bom'           : 'off',
      'use-isnan'             : 'error',
      'valid-jsdoc'           : 'off',
      'valid-typeof'          : 'error',
      'vars-on-top'           : 'off',
      'wrap-iife'             : 'off',
      'wrap-regex'            : 'off',
      'yield-star-spacing'    : ['error', 'after'],
      'yoda'                  : 'off',
    },
  },
]
